# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_detail.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 462)
        MainWindow.setStyleSheet("border-color: rgb(60, 12, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setStyleSheet("#mainWidget {\n"
"                        background-color: #fafafa;\n"
"                        border-width: 1px 1px 1px 1px;\n"
"                        border-style: solid;\n"
"                        border-color: rgb(160,160,160);\n"
"                        border-radius:6px;\n"
"                        }\n"
"                        QPushButton {\n"
"\n"
"                        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(61, 159, 232 ,\n"
"                        255), stop:1 rgba(89, 183, 252, 255));\n"
"                        padding:10px;\n"
"                        color:white;\n"
"                        border-radius:10px;\n"
"\n"
"                        }\n"
"                        #close_button {\n"
"                        padding:5px;\n"
"                        border-radius:15px;\n"
"                        }\n"
"\n"
"                        QLineEdit {\n"
"                        border-width: 1px 1px 1px 1px;\n"
"                        border-style: solid;\n"
"                        border-color: rgb(160,160,160);\n"
"                        border-radius:3px;\n"
"                        }\n"
"                    ")
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.close_button = QtWidgets.QPushButton(self.mainWidget)
        self.close_button.setMaximumSize(QtCore.QSize(15, 15))
        self.close_button.setBaseSize(QtCore.QSize(17, 17))
        self.close_button.setStyleSheet("background-color: #f46b72;\n"
"                                        border-radius:7px;\n"
"                                    ")
        self.close_button.setText("")
        self.close_button.setAutoDefault(False)
        self.close_button.setDefault(False)
        self.close_button.setFlat(False)
        self.close_button.setObjectName("close_button")
        self.gridLayout.addWidget(self.close_button, 0, 2, 1, 1)
        self.title_button_2 = QtWidgets.QPushButton(self.mainWidget)
        self.title_button_2.setMaximumSize(QtCore.QSize(15, 15))
        self.title_button_2.setStyleSheet("background-color: #f9c846;\n"
"                                        border-radius:7px;\n"
"                                    ")
        self.title_button_2.setText("")
        self.title_button_2.setObjectName("title_button_2")
        self.gridLayout.addWidget(self.title_button_2, 0, 1, 1, 1)
        self.title_button_3 = QtWidgets.QPushButton(self.mainWidget)
        self.title_button_3.setMinimumSize(QtCore.QSize(16, 0))
        self.title_button_3.setMaximumSize(QtCore.QSize(15, 15))
        self.title_button_3.setStyleSheet("background-color: #3fb89f;\n"
"                                        border-radius:7px;\n"
"                                    ")
        self.title_button_3.setText("")
        self.title_button_3.setObjectName("title_button_3")
        self.gridLayout.addWidget(self.title_button_3, 0, 0, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.url_input = QtWidgets.QLineEdit(self.mainWidget)
        self.url_input.setText("")
        self.url_input.setObjectName("url_input")
        self.horizontalLayout.addWidget(self.url_input)
        self.selected_button = QtWidgets.QPushButton(self.mainWidget)
        self.selected_button.setStyleSheet("padding:3px;\n"
"                                                border-radius:1px;\n"
"                                            ")
        self.selected_button.setObjectName("selected_button")
        self.horizontalLayout.addWidget(self.selected_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.fengmian = QtWidgets.QLabel(self.mainWidget)
        self.fengmian.setObjectName("fengmian")
        self.verticalLayout_2.addWidget(self.fengmian)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.book_name = QtWidgets.QLineEdit(self.mainWidget)
        self.book_name.setText("")
        self.book_name.setObjectName("book_name")
        self.horizontalLayout_7.addWidget(self.book_name)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.author = QtWidgets.QLineEdit(self.mainWidget)
        self.author.setText("")
        self.author.setObjectName("author")
        self.horizontalLayout_2.addWidget(self.author)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.mode_name = QtWidgets.QLineEdit(self.mainWidget)
        self.mode_name.setText("")
        self.mode_name.setObjectName("mode_name")
        self.horizontalLayout_6.addWidget(self.mode_name)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.status = QtWidgets.QLineEdit(self.mainWidget)
        self.status.setText("")
        self.status.setObjectName("status")
        self.horizontalLayout_5.addWidget(self.status)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.label_10 = QtWidgets.QLabel(self.mainWidget)
        self.label_10.setMaximumSize(QtCore.QSize(1600000, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setScaledContents(False)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.progress_obj = QtWidgets.QProgressBar(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.progress_obj.setFont(font)
        self.progress_obj.setStyleSheet("color:white;\n"
"border-radius:10px;")
        self.progress_obj.setMinimum(0)
        self.progress_obj.setMaximum(100)
        self.progress_obj.setProperty("value", 0)
        self.progress_obj.setTextVisible(True)
        self.progress_obj.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progress_obj.setObjectName("progress_obj")
        self.horizontalLayout_4.addWidget(self.progress_obj)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.catalog_table = QtWidgets.QTableWidget(self.mainWidget)
        self.catalog_table.setShowGrid(True)
        self.catalog_table.setRowCount(1)
        self.catalog_table.setColumnCount(1)
        self.catalog_table.setObjectName("catalog_table")
        self.verticalLayout_4.addWidget(self.catalog_table)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.horizontalLayout_11.setStretch(0, 4)
        self.horizontalLayout_11.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, 10, 10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.download_button = QtWidgets.QPushButton(self.mainWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.download_button.setFont(font)
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_3.addWidget(self.download_button)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addWidget(self.mainWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NoverDownloader"))
        self.label_7.setText(_translate("MainWindow", "书籍详情"))
        self.label.setText(_translate("MainWindow", "网址:"))
        self.selected_button.setText(_translate("MainWindow", "查询"))
        self.label_5.setText(_translate("MainWindow", "封面"))
        self.fengmian.setText(_translate("MainWindow", "图片"))
        self.label_2.setText(_translate("MainWindow", "书名:"))
        self.label_4.setText(_translate("MainWindow", "作者:"))
        self.label_8.setText(_translate("MainWindow", "匹配模式:"))
        self.label_6.setText(_translate("MainWindow", "状态:"))
        self.label_10.setText(_translate("MainWindow", "  人有本命珠，觉醒后或为意珠、或为体珠，如手串分别在左右手腕处盘旋。天珠如人类之双胞胎，当意、体双珠同时出现在一个人身上的时候，即为天珠。修炼体珠者是为体珠师，修炼意珠者是为意珠师，而修炼天珠者自然即是天珠师。天珠师最高为十二双珠，因此，它的修炼过程也被称之为：天珠十二变。我们的主角就是一位修炼着天珠变的弓箭手。"))
        self.label_9.setText(_translate("MainWindow", "下载进度:"))
        self.progress_obj.setFormat(_translate("MainWindow", "  %p%"))
        self.label_3.setText(_translate("MainWindow", "目录:"))
        self.pushButton_2.setText(_translate("MainWindow", "返回"))
        self.download_button.setText(_translate("MainWindow", "开始下载"))
